// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'router'], function($, _, Backbone, Router) {
    var initialize;

    initialize = function() {
    	console.log("init!")
      Router.initialize();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
